create database SkyPremier;
use SkyPremier;
 
CREATE TABLE LOAI_THANH_VIEN (
    MA_LOAI VARCHAR(10) NOT NULL PRIMARY KEY,
    TEN_LOAI VARCHAR(50) NOT NULL,
    NGUONG_DIEM INT NOT NULL CHECK (NGUONG_DIEM >= 0)
);

CREATE TABLE KHACH_HANG (
    MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
    HO_TEN VARCHAR(100) NOT NULL,
    NGAY_SINH DATE,
    GIOI_TINH CHAR(1) CHECK (GIOI_TINH IN ('M', 'F')),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SDT VARCHAR(15) NOT NULL,
    MAT_KHAU VARCHAR(255) NOT NULL,
    MA_LOAI VARCHAR(10) NOT NULL,
    FOREIGN KEY (MA_LOAI) REFERENCES LOAI_THANH_VIEN(MA_LOAI)
);

CREATE TABLE CHUYEN_BAY (
    MACHUYEN VARCHAR(10) NOT NULL PRIMARY KEY,
    SAN_BAY_DI VARCHAR(50) NOT NULL,
    SAN_BAY_DEN VARCHAR(50) NOT NULL,
    GIO_DI DATETIME NOT NULL,
    GIO_DEN DATETIME NOT NULL,
    SO_HIEU_CHUYEN_BAY VARCHAR(20) NOT NULL UNIQUE,
    HANG_HANG_KHONG VARCHAR(50) NOT NULL,
    TRANG_THAI VARCHAR(20) NOT NULL
);

CREATE TABLE GIA_VE_THEO_HANG (
    MACHUYEN VARCHAR(10) NOT NULL,
    MA_HANGVE VARCHAR(10) NOT NULL,
    GIA DECIMAL(15, 2) NOT NULL CHECK (GIA >= 0),

    PRIMARY KEY (MACHUYEN, MA_HANGVE),
    FOREIGN KEY (MACHUYEN) REFERENCES CHUYEN_BAY(MACHUYEN),
    FOREIGN KEY (MA_HANGVE) REFERENCES HANG_VE(MA_HANGVE)
);

CREATE TABLE DAT_VE (
    MADATVE VARCHAR(10) NOT NULL PRIMARY KEY,
    MAKH VARCHAR(10) NOT NULL,
    MACHUYEN VARCHAR(10) NOT NULL,
    NGAY_DAT DATETIME NOT NULL,
    TONG_TIEN DECIMAL(15, 2) NOT NULL CHECK (TONG_TIEN >= 0),
    TRANG_THAI ENUM('Chờ thanh toán', 'Đã thanh toán', 'Đã hủy') NOT NULL,

    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    FOREIGN KEY (MACHUYEN) REFERENCES CHUYEN_BAY(MACHUYEN)
);

CREATE TABLE HANG_VE (
    MA_HANGVE VARCHAR(10) NOT NULL PRIMARY KEY,
    TEN_HANGVE VARCHAR(50) NOT NULL
);

CREATE TABLE VE_CHI_TIET (
    MAVE VARCHAR(10) NOT NULL PRIMARY KEY,
    MADATVE VARCHAR(10) NOT NULL,
    HO_TEN_HANH_KHACH VARCHAR(100) NOT NULL,
    SO_GHE VARCHAR(10) NOT NULL,
    MA_HANGVE VARCHAR(10) NOT NULL,
    GIA_VE DECIMAL(15, 2) NOT NULL CHECK (GIA_VE >= 0),
    DICH_VU_BO_SUNG TEXT,

    FOREIGN KEY (MADATVE) REFERENCES DAT_VE(MADATVE),
    FOREIGN KEY (MA_HANGVE) REFERENCES HANG_VE(MA_HANGVE)
);

CREATE TABLE HOA_DON (
    MAHD VARCHAR(10) NOT NULL PRIMARY KEY,
    MADATVE VARCHAR(10) NOT NULL,
    NGAY_LAP DATE NOT NULL,
    TONG_TIEN DECIMAL(15, 2) NOT NULL CHECK (TONG_TIEN >= 0),
    TRANG_THAI ENUM('Chưa thanh toán', 'Đã thanh toán', 'Đã hủy') NOT NULL,

    FOREIGN KEY (MADATVE) REFERENCES DAT_VE(MADATVE)
);

CREATE TABLE KHUYEN_MAI (
    MAKM VARCHAR(10) NOT NULL PRIMARY KEY,
    TIEU_DE VARCHAR(100) NOT NULL,
    NOI_DUNG TEXT,
    NGAY_BAT_DAU DATE NOT NULL,
    NGAY_KET_THUC DATE NOT NULL,
    DOI_TUONG_AP_DUNG VARCHAR(50),
    CHECK (NGAY_KET_THUC >= NGAY_BAT_DAU)
);

CREATE TABLE KHUYEN_MAI_KHACH_HANG(
    MAKM VARCHAR(10) NOT NULL,
    MAKH VARCHAR(10) NOT NULL,
    NGAY_AP_DUNG DATE NOT NULL,
    TRANG_THAI ENUM('Đã dùng', 'Chưa dùng', 'Hết hạn'),

    PRIMARY KEY (MAKM, MAKH),
    FOREIGN KEY (MAKM) REFERENCES KHUYEN_MAI(MAKM),
    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)
);

CREATE TABLE TICH_DIEM (
    MA_TD VARCHAR(10) NOT NULL PRIMARY KEY,
    MAKH VARCHAR(10) NOT NULL,
    NGUON_TICH_DIEM VARCHAR(50) NOT NULL,
    DIEM INT NOT NULL CHECK (DIEM >= 0),
    NGAY_GHI_NHAN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)
);

CREATE TABLE TONG_DIEM (
    MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
    TONG_DIEM INT NOT NULL DEFAULT 0 CHECK (TONG_DIEM >= 0),
    MA_LOAI VARCHAR(10) NOT NULL,

    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    FOREIGN KEY (MA_LOAI) REFERENCES LOAI_THANH_VIEN(MA_LOAI)
);

CREATE TABLE THONG_BAO (
    MATHONGBAO VARCHAR(10) NOT NULL PRIMARY KEY,
    MAKH VARCHAR(10) NOT NULL,
    NOI_DUNG TEXT NOT NULL,
    NGAY_GUI DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOAI_THONG_BAO VARCHAR(50) NOT NULL,

    FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH)
);